version: 1

before:
    hooks:
        - cd ./cli && go mod tidy

builds:
    - id: kmd
      main: ./cli
      binary: kmd
      goos:
          - linux
      goarch:
          - amd64
          - arm64
      env:
          - CGO_ENABLED=0
      flags:
          - -trimpath
      ldflags:
          - -s -w
          - -X main.version={{.Version}}

archives:
    - id: default
      format: tar.gz
      name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
      files:
          - LICENSE*
          - README*

release:
    github:
        owner: abishek77s
        name: kmd
    extra_files:
        - glob: dist/kmd_*/kmd
          name_template: "kmd-{{ .Os }}-{{ .Arch }}"

checksum:
    name_template: "checksums.txt"

changelog:
    sort: asc
    filters:
        exclude:
            - "^docs:"
            - "^test:"
